/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CatalogGame {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface CraftableItem {
  'id' : string,
  'requiredSupplies' : Array<Supply>,
  'name' : string,
  'values' : Values,
  'upgrades' : Array<Upgrade>,
  'category' : ItemCategory,
}
export interface Game {
  'id' : string,
  'remoteDataSources' : Array<RemoteDataSource>,
  'name' : string,
  'description' : string,
}
export type ItemCategory = { 'tools' : null } |
  { 'armor' : null } |
  { 'food' : null } |
  { 'buildingMaterials' : null } |
  { 'weapons' : null } |
  { 'decorations' : null };
export interface RemoteDataSource {
  'id' : string,
  'url' : string,
  'description' : string,
}
export interface Supply {
  'id' : string,
  'name' : string,
  'quantity' : bigint,
  'category' : ItemCategory,
}
export type Time = bigint;
export interface UpdateStatus {
  'status' : { 'idle' : null } |
    { 'success' : null } |
    { 'inProgress' : null } |
    { 'failed' : { 'error' : string } },
  'lastUpdated' : [] | [Time],
}
export interface Upgrade {
  'id' : string,
  'requiredSupplies' : Array<Supply>,
  'cost' : bigint,
  'name' : string,
  'level' : bigint,
}
export interface Values {
  'stats' : [] | [string],
  'durability' : [] | [bigint],
  'sellValue' : [] | [bigint],
}
export interface _SERVICE {
  'addCatalogGame' : ActorMethod<[CatalogGame], undefined>,
  'getCatalogGame' : ActorMethod<[string], [] | [CatalogGame]>,
  'getCatalogGames' : ActorMethod<[], Array<CatalogGame>>,
  'getGame' : ActorMethod<[string], [] | [Game]>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getItem' : ActorMethod<[string, string], [] | [CraftableItem]>,
  'getItems' : ActorMethod<[string], Array<CraftableItem>>,
  'getItemsByCategory' : ActorMethod<
    [string, ItemCategory],
    Array<CraftableItem>
  >,
  'getUpdateStatus' : ActorMethod<[string], [] | [UpdateStatus]>,
  'searchItems' : ActorMethod<[string], Array<CraftableItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];