/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CatalogGame = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const RemoteDataSource = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'description' : IDL.Text,
});
export const Game = IDL.Record({
  'id' : IDL.Text,
  'remoteDataSources' : IDL.Vec(RemoteDataSource),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ItemCategory = IDL.Variant({
  'tools' : IDL.Null,
  'armor' : IDL.Null,
  'food' : IDL.Null,
  'buildingMaterials' : IDL.Null,
  'weapons' : IDL.Null,
  'decorations' : IDL.Null,
});
export const Supply = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : ItemCategory,
});
export const Values = IDL.Record({
  'stats' : IDL.Opt(IDL.Text),
  'durability' : IDL.Opt(IDL.Nat),
  'sellValue' : IDL.Opt(IDL.Nat),
});
export const Upgrade = IDL.Record({
  'id' : IDL.Text,
  'requiredSupplies' : IDL.Vec(Supply),
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'level' : IDL.Nat,
});
export const CraftableItem = IDL.Record({
  'id' : IDL.Text,
  'requiredSupplies' : IDL.Vec(Supply),
  'name' : IDL.Text,
  'values' : Values,
  'upgrades' : IDL.Vec(Upgrade),
  'category' : ItemCategory,
});
export const Time = IDL.Int;
export const UpdateStatus = IDL.Record({
  'status' : IDL.Variant({
    'idle' : IDL.Null,
    'success' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  }),
  'lastUpdated' : IDL.Opt(Time),
});

export const idlService = IDL.Service({
  'addCatalogGame' : IDL.Func([CatalogGame], [], []),
  'getCatalogGame' : IDL.Func([IDL.Text], [IDL.Opt(CatalogGame)], ['query']),
  'getCatalogGames' : IDL.Func([], [IDL.Vec(CatalogGame)], ['query']),
  'getGame' : IDL.Func([IDL.Text], [IDL.Opt(Game)], ['query']),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getItem' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CraftableItem)],
      ['query'],
    ),
  'getItems' : IDL.Func([IDL.Text], [IDL.Vec(CraftableItem)], ['query']),
  'getItemsByCategory' : IDL.Func(
      [IDL.Text, ItemCategory],
      [IDL.Vec(CraftableItem)],
      ['query'],
    ),
  'getProductionItems' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CraftableItem)],
      ['query'],
    ),
  'getUpdateStatus' : IDL.Func([IDL.Text], [IDL.Opt(UpdateStatus)], ['query']),
  'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(CraftableItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CatalogGame = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const RemoteDataSource = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'description' : IDL.Text,
  });
  const Game = IDL.Record({
    'id' : IDL.Text,
    'remoteDataSources' : IDL.Vec(RemoteDataSource),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ItemCategory = IDL.Variant({
    'tools' : IDL.Null,
    'armor' : IDL.Null,
    'food' : IDL.Null,
    'buildingMaterials' : IDL.Null,
    'weapons' : IDL.Null,
    'decorations' : IDL.Null,
  });
  const Supply = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : ItemCategory,
  });
  const Values = IDL.Record({
    'stats' : IDL.Opt(IDL.Text),
    'durability' : IDL.Opt(IDL.Nat),
    'sellValue' : IDL.Opt(IDL.Nat),
  });
  const Upgrade = IDL.Record({
    'id' : IDL.Text,
    'requiredSupplies' : IDL.Vec(Supply),
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'level' : IDL.Nat,
  });
  const CraftableItem = IDL.Record({
    'id' : IDL.Text,
    'requiredSupplies' : IDL.Vec(Supply),
    'name' : IDL.Text,
    'values' : Values,
    'upgrades' : IDL.Vec(Upgrade),
    'category' : ItemCategory,
  });
  const Time = IDL.Int;
  const UpdateStatus = IDL.Record({
    'status' : IDL.Variant({
      'idle' : IDL.Null,
      'success' : IDL.Null,
      'inProgress' : IDL.Null,
      'failed' : IDL.Record({ 'error' : IDL.Text }),
    }),
    'lastUpdated' : IDL.Opt(Time),
  });
  
  return IDL.Service({
    'addCatalogGame' : IDL.Func([CatalogGame], [], []),
    'getCatalogGame' : IDL.Func([IDL.Text], [IDL.Opt(CatalogGame)], ['query']),
    'getCatalogGames' : IDL.Func([], [IDL.Vec(CatalogGame)], ['query']),
    'getGame' : IDL.Func([IDL.Text], [IDL.Opt(Game)], ['query']),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getItem' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CraftableItem)],
        ['query'],
      ),
    'getItems' : IDL.Func([IDL.Text], [IDL.Vec(CraftableItem)], ['query']),
    'getItemsByCategory' : IDL.Func(
        [IDL.Text, ItemCategory],
        [IDL.Vec(CraftableItem)],
        ['query'],
      ),
    'getProductionItems' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CraftableItem)],
        ['query'],
      ),
    'getUpdateStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UpdateStatus)],
        ['query'],
      ),
    'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(CraftableItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };