/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Game {
    id: string;
    remoteDataSources: Array<RemoteDataSource>;
    name: string;
    description: string;
}
export type Time = bigint;
export interface RemoteDataSource {
    id: string;
    url: string;
    description: string;
}
export interface UpdateStatus {
    status: {
        __kind__: "idle";
        idle: null;
    } | {
        __kind__: "success";
        success: null;
    } | {
        __kind__: "inProgress";
        inProgress: null;
    } | {
        __kind__: "failed";
        failed: {
            error: string;
        };
    };
    lastUpdated?: Time;
}
export interface Upgrade {
    id: string;
    requiredSupplies: Array<Supply>;
    cost: bigint;
    name: string;
    level: bigint;
}
export interface Supply {
    id: string;
    name: string;
    quantity: bigint;
    category: ItemCategory;
}
export interface CraftableItem {
    id: string;
    requiredSupplies: Array<Supply>;
    name: string;
    values: Values;
    upgrades: Array<Upgrade>;
    category: ItemCategory;
}
export interface Values {
    stats?: string;
    durability?: bigint;
    sellValue?: bigint;
}
export interface CatalogGame {
    id: string;
    name: string;
    description: string;
}
export enum ItemCategory {
    tools = "tools",
    armor = "armor",
    food = "food",
    buildingMaterials = "buildingMaterials",
    weapons = "weapons",
    decorations = "decorations"
}
export interface backendInterface {
    addCatalogGame(game: CatalogGame): Promise<void>;
    getCatalogGame(gameId: string): Promise<CatalogGame | null>;
    getCatalogGames(): Promise<Array<CatalogGame>>;
    getGame(gameId: string): Promise<Game | null>;
    getGames(): Promise<Array<Game>>;
    getItem(gameId: string, itemId: string): Promise<CraftableItem | null>;
    getItems(gameId: string): Promise<Array<CraftableItem>>;
    getItemsByCategory(gameId: string, category: ItemCategory): Promise<Array<CraftableItem>>;
    getProductionItems(gameId: string): Promise<Array<CraftableItem>>;
    getUpdateStatus(gameId: string): Promise<UpdateStatus | null>;
    searchItems(searchTerm: string): Promise<Array<CraftableItem>>;
}
import type { CatalogGame as _CatalogGame, CraftableItem as _CraftableItem, Game as _Game, ItemCategory as _ItemCategory, Supply as _Supply, Time as _Time, UpdateStatus as _UpdateStatus, Upgrade as _Upgrade, Values as _Values } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCatalogGame(arg0: CatalogGame): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCatalogGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCatalogGame(arg0);
            return result;
        }
    }
    async getCatalogGame(arg0: string): Promise<CatalogGame | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogGame(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogGame(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogGames(): Promise<Array<CatalogGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogGames();
            return result;
        }
    }
    async getGame(arg0: string): Promise<Game | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGames();
            return result;
        }
    }
    async getItem(arg0: string, arg1: string): Promise<CraftableItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItems(arg0: string): Promise<Array<CraftableItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItems(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItems(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByCategory(arg0: string, arg1: ItemCategory): Promise<Array<CraftableItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByCategory(arg0, to_candid_ItemCategory_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByCategory(arg0, to_candid_ItemCategory_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionItems(arg0: string): Promise<Array<CraftableItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionItems(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionItems(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpdateStatus(arg0: string): Promise<UpdateStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpdateStatus(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpdateStatus(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchItems(arg0: string): Promise<Array<CraftableItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchItems(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchItems(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CraftableItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CraftableItem): CraftableItem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ItemCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemCategory): ItemCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Supply_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Supply): Supply {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateStatus): UpdateStatus {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Upgrade_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Upgrade): Upgrade {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Values_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Values): Values {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CatalogGame]): CatalogGame | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Game]): Game | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpdateStatus]): UpdateStatus | null {
    return value.length === 0 ? null : from_candid_UpdateStatus_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CraftableItem]): CraftableItem | null {
    return value.length === 0 ? null : from_candid_CraftableItem_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stats: [] | [string];
    durability: [] | [bigint];
    sellValue: [] | [bigint];
}): {
    stats?: string;
    durability?: bigint;
    sellValue?: bigint;
} {
    return {
        stats: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.stats)),
        durability: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.durability)),
        sellValue: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.sellValue))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    requiredSupplies: Array<_Supply>;
    cost: bigint;
    name: string;
    level: bigint;
}): {
    id: string;
    requiredSupplies: Array<Supply>;
    cost: bigint;
    name: string;
    level: bigint;
} {
    return {
        id: value.id,
        requiredSupplies: from_candid_vec_n6(_uploadFile, _downloadFile, value.requiredSupplies),
        cost: value.cost,
        name: value.name,
        level: value.level
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        idle: null;
    } | {
        success: null;
    } | {
        inProgress: null;
    } | {
        failed: {
            error: string;
        };
    };
    lastUpdated: [] | [_Time];
}): {
    status: {
        __kind__: "idle";
        idle: null;
    } | {
        __kind__: "success";
        success: null;
    } | {
        __kind__: "inProgress";
        inProgress: null;
    } | {
        __kind__: "failed";
        failed: {
            error: string;
        };
    };
    lastUpdated?: Time;
} {
    return {
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        lastUpdated: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.lastUpdated))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    requiredSupplies: Array<_Supply>;
    name: string;
    values: _Values;
    upgrades: Array<_Upgrade>;
    category: _ItemCategory;
}): {
    id: string;
    requiredSupplies: Array<Supply>;
    name: string;
    values: Values;
    upgrades: Array<Upgrade>;
    category: ItemCategory;
} {
    return {
        id: value.id,
        requiredSupplies: from_candid_vec_n6(_uploadFile, _downloadFile, value.requiredSupplies),
        name: value.name,
        values: from_candid_Values_n11(_uploadFile, _downloadFile, value.values),
        upgrades: from_candid_vec_n15(_uploadFile, _downloadFile, value.upgrades),
        category: from_candid_ItemCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    quantity: bigint;
    category: _ItemCategory;
}): {
    id: string;
    name: string;
    quantity: bigint;
    category: ItemCategory;
} {
    return {
        id: value.id,
        name: value.name,
        quantity: value.quantity,
        category: from_candid_ItemCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tools: null;
} | {
    armor: null;
} | {
    food: null;
} | {
    buildingMaterials: null;
} | {
    weapons: null;
} | {
    decorations: null;
}): ItemCategory {
    return "tools" in value ? ItemCategory.tools : "armor" in value ? ItemCategory.armor : "food" in value ? ItemCategory.food : "buildingMaterials" in value ? ItemCategory.buildingMaterials : "weapons" in value ? ItemCategory.weapons : "decorations" in value ? ItemCategory.decorations : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    success: null;
} | {
    inProgress: null;
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "idle";
    idle: null;
} | {
    __kind__: "success";
    success: null;
} | {
    __kind__: "inProgress";
    inProgress: null;
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "idle" in value ? {
        __kind__: "idle",
        idle: value.idle
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Upgrade>): Array<Upgrade> {
    return value.map((x)=>from_candid_Upgrade_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CraftableItem>): Array<CraftableItem> {
    return value.map((x)=>from_candid_CraftableItem_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Supply>): Array<Supply> {
    return value.map((x)=>from_candid_Supply_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ItemCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCategory): _ItemCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCategory): {
    tools: null;
} | {
    armor: null;
} | {
    food: null;
} | {
    buildingMaterials: null;
} | {
    weapons: null;
} | {
    decorations: null;
} {
    return value == ItemCategory.tools ? {
        tools: null
    } : value == ItemCategory.armor ? {
        armor: null
    } : value == ItemCategory.food ? {
        food: null
    } : value == ItemCategory.buildingMaterials ? {
        buildingMaterials: null
    } : value == ItemCategory.weapons ? {
        weapons: null
    } : value == ItemCategory.decorations ? {
        decorations: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
